
modLoader = "javafml" #mandatory

loaderVersion = "${loader_version_range}" #mandatory

license = "${mod_license}"

[[mods]] #mandatory

modId = "${mod_id}" #mandatory

version = "${mod_version}" #mandatory

displayName = "${mod_name}" #mandatory

authors = "${mod_authors}" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''${mod_description}'''

[[mixins]]
config = "shotgunmod.mixins.json"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies."${mod_id}"]] #optional
# the modid of the dependency
modId = "neoforge" #mandatory

type = "required" #mandatory

versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
# Here's another dependency
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "geckolib"
type = "required"
versionRange = "[4.5.8,)"
ordering = "NONE"
side = "BOTH"